runtime: python37


entrypoint: gunicorn -t 3600 -b :$PORT main:app --workers 1 --threads 1 --worker-class gthread 
automatic_scaling:
  min_instances: 1
  max_instances: 1


handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: client/build/static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
